version: "3"
services:
  postgres:
    image: postgres
    network_mode: bridge
    container_name: postgres-docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=room_reservation
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: springbootapp:latest
    network_mode: bridge
    container_name: springbootapp
    expose:
      - 8085
    ports:
      - 8085:8085
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres-data: